REG ADD "HKEY_LOCAL_MACHINE\Software\WOW6432Node\Multi Theft Auto: San Andreas All\Common" /v "GTA:SA Path" /f /t REG_SZ /d "M:\CLEAN\client-Meta-1.6\Bin"
REG ADD "HKEY_LOCAL_MACHINE\Software\WOW6432Node\Multi Theft Auto: San Andreas All\Common" /v "File Cache Path" /f /t REG_SZ /d "M:\CLEAN\client-Meta-1.6\Bin\mods\deathmatch"
REG ADD "HKEY_LOCAL_MACHINE\Software\Multi Theft Auto: San Andreas All\Common" /v "GTA:SA Path" /f /t REG_SZ /d "M:\CLEAN\client-Meta-1.6\Bin"
REG ADD "HKEY_LOCAL_MACHINE\Software\Multi Theft Auto: San Andreas All\Common" /v "File Cache Path" /f /t REG_SZ /d "M:\CLEAN\client-Meta-1.6\Bin\mods\deathmatch"
REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\MTA NORTRP\Common" /v "GTA:SA Path" /f /t REG_SZ /d "M:\CLEAN\client-Meta-1.6\Bin"
REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\MTA NORTRP\Common" /v "File Cache Path" /f /t REG_SZ /d "M:\CLEAN\client-Meta-1.6\Bin\mods\deathmatch"
REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\MTA NORTRP\Common" /v "GTA:SA Path" /f /t REG_SZ /d "M:\CLEAN\client-Meta-1.6\Bin"
REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\MTA NORTRP\Common" /v "File Cache Path" /f /t REG_SZ /d "M:\CLEAN\client-Meta-1.6\Bin\mods\deathmatch"
REG ADD "HKEY_CURRENT_USER\Software\WOW6432Node\Multi Theft Auto: San Andreas All\Common" /v "GTA:SA Path" /f /t REG_SZ /d "M:\CLEAN\client-Meta-1.6\Bin"
REG ADD "HKEY_CURRENT_USER\Software\WOW6432Node\Multi Theft Auto: San Andreas All\Common" /v "File Cache Path" /f /t REG_SZ /d "M:\CLEAN\client-Meta-1.6\Bin\mods\deathmatch"
REG ADD "HKEY_CURRENT_USER\Software\Multi Theft Auto: San Andreas All\Common" /v "GTA:SA Path" /f /t REG_SZ /d "M:\CLEAN\client-Meta-1.6\Bin"
REG ADD "HKEY_CURRENT_USER\Software\Multi Theft Auto: San Andreas All\Common" /v "File Cache Path" /f /t REG_SZ /d "M:\CLEAN\client-Meta-1.6\Bin\mods\deathmatch"
REG ADD "HKEY_CURRENT_USER\Software\WOW6432Node\MTA NORTRP\Common" /v "GTA:SA Path" /f /t REG_SZ /d "M:\CLEAN\client-Meta-1.6\Bin"
REG ADD "HKEY_CURRENT_USER\Software\WOW6432Node\MTA NORTRP\Common" /v "File Cache Path" /f /t REG_SZ /d "M:\CLEAN\client-Meta-1.6\Bin\mods\deathmatch"
REG ADD "HKEY_CURRENT_USER\Software\MTA NORTRP\Common" /v "GTA:SA Path" /f /t REG_SZ /d "M:\CLEAN\client-Meta-1.6\Bin"
REG ADD "HKEY_CURRENT_USER\Software\MTA NORTRP\Common" /v "File Cache Path" /f /t REG_SZ /d "M:\CLEAN\client-Meta-1.6\Bin\mods\deathmatch"
